from datetime import datetime
from struct_excel.models import (
    RawRow,
    Supervisor,
    Course,
    Student,
    Session,
    Enrollment,
    Gender,
    Sector,
    SessionMode,
)

RAW: list[RawRow] = [
    RawRow(
        reg_date=datetime(2025, 12, 29),
        student_full_name="AAS",
        student_email="aas.@email.gov.my",
        student_company="Royal Malaysian Police",
        student_job_title="Inspector",
        country="MY",
        exception="None",
        phone="132755736",
        course="Feb 19 2026 (to Feb 20 2026) @ 9.30am MYT | [Online] Cybersecurity Tools [3h]",
        gender="Male",
        sector="Government",
        supervisor_name="HYL",
        supervisor_email="hyl.@email.gov.my",
        it_background="Yes",
        experience=">5 years",
        completed="Yes",
        payment_status="Paid",
    ),
    RawRow(
        reg_date=datetime(2026, 1, 13),
        student_full_name="SAB",
        student_email="sab.@email.gov.my",
        student_company="KEMENTERIAN SUMBER ASLI DAN KELESTARIAN ALAM",
        student_job_title="IT OFFICER",
        country="MY",
        exception="None",
        phone="192372661",
        course="Feb 19 2026 (to Feb 20 2026) @ 9.30am MYT | [Online] Cybersecurity Tools [3h]",
        gender="Female",
        sector="Government",
        supervisor_name="HBB",
        supervisor_email="hbb.@email.gov.my",
        it_background="Yes",
        experience=">5 years",
        completed="No",
        payment_status="Pending",
    ),
    RawRow(
        reg_date=datetime(2026, 1, 13),
        student_full_name="LbM",
        student_email="lbm.@email.gov.my",
        student_company="MACC",
        student_job_title="IT Officer",
        country="MY",
        exception="Schedule conflict",
        phone="197515425",
        course="Feb 19 2026 (to Feb 20 2026) @ 9.30am MYT | [Online] Cybersecurity Tools [3h]",
        gender="Female",
        sector="Government",
        supervisor_name="MSb",
        supervisor_email="msb.@email.gov.my",
        it_background="Yes",
        experience="1-5 years",
        completed="Yes",
        payment_status="Paid",
    ),
    RawRow(
        reg_date=datetime(2026, 1, 23),
        student_full_name="SBN",
        student_email="sbn.@email.gov.my",
        student_company="Malaysian Meritime Enforcement Agency",
        student_job_title="IT Officer",
        country="MY",
        exception="None",
        phone="60389957559",
        course="Feb 19 2026 (to Feb 20 2026) @ 9.30am MYT | [Online] Cybersecurity Tools [3h]",
        gender="Male",
        sector="Government",
        supervisor_name="SBP",
        supervisor_email="sbp.@email.gov.my",
        it_background="Yes",
        experience=">5 years",
        completed="Yes",
        payment_status="Paid",
    ),
    RawRow(
        reg_date=datetime(2025, 12, 22),
        student_full_name="IZB",
        student_email="izb.@student.my",
        student_company="Universiti Malaysia Sabah",
        student_job_title="Student",
        country="MY",
        exception="CNext",
        phone="1127371315",
        course="Feb 19 2026 (to Feb 20 2026) @ 9.30am MYT | [Online] Cybersecurity Tools [3h]",
        gender="Female",
        sector="Student",
        supervisor_name="",
        supervisor_email="",
        it_background="Yes",
        experience="Not Applicable (Students)",
        completed="Yes",
        payment_status="Paid",
    ),
    RawRow(
        reg_date=datetime(2025, 12, 7),
        student_full_name="DK",
        student_email="dk.@student.my",
        student_company="Panimalar Engineering College",
        student_job_title="Student",
        country="?",
        exception="None",
        phone="9884177003",
        course="Feb 19 2026 (to Feb 20 2026) @ 9.30am MYT | [Online] Cybersecurity Tools [3h]",
        gender="Male",
        sector="Student",
        supervisor_name="",
        supervisor_email="",
        it_background="Yes",
        experience="1-5 years",
        completed="Yes",
        payment_status="Paid",
    ),
    RawRow(
        reg_date=datetime(2026, 1, 22),
        student_full_name="NGW",
        student_email="ngw.@private.my",
        student_company="OSK Group",
        student_job_title="Junior Engineer",
        country="MY",
        exception="None",
        phone="192233121",
        course="Feb 23 2026 (to Feb 27 2026) | RCC SOC Analyst & Security Manager",
        gender="Female",
        sector="Private",
        supervisor_name="",
        supervisor_email="",
        it_background="Yes",
        experience="<1 year",
        completed="Yes",
        payment_status="Paid",
    ),
    RawRow(
        reg_date=datetime(2026, 2, 11),
        student_full_name="SBA",
        student_email="sba.@email.gov.my",
        student_company="National Pharmaceutical Regulatory Agency",
        student_job_title="Pharmacist",
        country="MY",
        exception="None",
        phone="012-4655460",
        course="Feb 24 2026 @ 9.30am MYT | Introduction to Identity & Access Management (IAM) [2h]",
        gender="Female",
        sector="Government",
        supervisor_name="AbH",
        supervisor_email="abh.@email.gov.my",
        it_background="No",
        experience="Nil",
        completed="No",
        payment_status="Pending",
    ),
]

EXPECTED_SUPERVISORS: list[Supervisor] = [
    Supervisor(supervisor_id=1, full_name="HYL", email="hyl.@email.gov.my"),
    Supervisor(supervisor_id=2, full_name="HBB", email="hbb.@email.gov.my"),
    Supervisor(supervisor_id=3, full_name="MSb", email="msb.@email.gov.my"),
    Supervisor(supervisor_id=4, full_name="SBP", email="sbp.@email.gov.my"),
    Supervisor(supervisor_id=5, full_name="AbH", email="abh.@email.gov.my"),
]

EXPECTED_COURSES: list[Course] = [
    Course(course_id=1, course_name="Cybersecurity Tools"),
    Course(course_id=2, course_name="RCC SOC Analyst & Security Manager"),
    Course(
        course_id=3, course_name="Introduction to Identity & Access Management (IAM)"
    ),
]

EXPECTED_STUDENTS: list[Student] = [
    Student(
        student_id=1,
        full_name="AAS",
        email="aas.@email.gov.my",
        gender=Gender.MALE,
        it_background=True,
        experience_min_years=5,
        experience_max_years=100,
        sector=Sector.GOVERNMENT,
        supervisor_id=1,
        company="Royal Malaysian Police",
        job_title="Inspector",
        country="MY",
        phone="132755736",
    ),
    Student(
        student_id=2,
        full_name="SAB",
        email="sab.@email.gov.my",
        gender=Gender.FEMALE,
        it_background=True,
        experience_min_years=5,
        experience_max_years=100,
        sector=Sector.GOVERNMENT,
        supervisor_id=2,
        company="KEMENTERIAN SUMBER ASLI DAN KELESTARIAN ALAM",
        job_title="IT OFFICER",
        country="MY",
        phone="192372661",
    ),
    Student(
        student_id=3,
        full_name="LbM",
        email="lbm.@email.gov.my",
        gender=Gender.FEMALE,
        it_background=True,
        experience_min_years=1,
        experience_max_years=5,
        sector=Sector.GOVERNMENT,
        supervisor_id=3,
        company="MACC",
        job_title="IT Officer",
        country="MY",
        phone="197515425",
    ),
    Student(
        student_id=4,
        full_name="SBN",
        email="sbn.@email.gov.my",
        gender=Gender.MALE,
        it_background=True,
        experience_min_years=5,
        experience_max_years=100,
        sector=Sector.GOVERNMENT,
        supervisor_id=4,
        company="Malaysian Meritime Enforcement Agency",
        job_title="IT Officer",
        country="MY",
        phone="60389957559",
    ),
    Student(
        student_id=5,
        full_name="IZB",
        email="izb.@student.my",
        gender=Gender.FEMALE,
        it_background=True,
        experience_min_years=0,
        experience_max_years=0,
        sector=Sector.STUDENT,
        supervisor_id=None,
        company="Universiti Malaysia Sabah",
        job_title="Student",
        country="MY",
        phone="1127371315",
    ),
    Student(
        student_id=6,
        full_name="DK",
        email="dk.@student.my",
        gender=Gender.MALE,
        it_background=True,
        experience_min_years=1,
        experience_max_years=5,
        sector=Sector.STUDENT,
        supervisor_id=None,
        company="Panimalar Engineering College",
        job_title="Student",
        country="?",
        phone="9884177003",
    ),
    Student(
        student_id=7,
        full_name="NGW",
        email="ngw.@private.my",
        gender=Gender.FEMALE,
        it_background=True,
        experience_min_years=0,
        experience_max_years=1,
        sector=Sector.PRIVATE,
        supervisor_id=None,
        company="OSK Group",
        job_title="Junior Engineer",
        country="MY",
        phone="192233121",
    ),
    Student(
        student_id=8,
        full_name="SBA",
        email="sba.@email.gov.my",
        gender=Gender.FEMALE,
        it_background=False,
        experience_min_years=0,
        experience_max_years=0,
        sector=Sector.GOVERNMENT,
        supervisor_id=5,
        company="National Pharmaceutical Regulatory Agency",
        job_title="Pharmacist",
        country="MY",
        phone="012-4655460",
    ),
]

EXPECTED_SESSIONS: list[Session] = [
    Session(
        session_id=1,
        course_id=1,
        start_datetime=datetime(2026, 2, 19),
        end_datetime=datetime(2026, 2, 20),
        mode=SessionMode.ONLINE,
        duration=3.0,
    ),
    Session(
        session_id=2,
        course_id=2,
        start_datetime=datetime(2026, 2, 23),
        end_datetime=datetime(2026, 2, 27),
        mode=SessionMode.OFFLINE,
        duration=0.0,
    ),
    Session(
        session_id=3,
        course_id=3,
        start_datetime=datetime(2026, 2, 24, 9, 30),
        end_datetime=datetime(2026, 2, 24, 9, 30),
        mode=SessionMode.OFFLINE,
        duration=2.0,
    ),
]

EXPECTED_ENROLLMENTS: list[Enrollment] = [
    Enrollment(
        enrollment_id=1,
        student_id=1,
        session_id=1,
        reg_date=datetime(2025, 12, 29),
        completed=True,
        payment_status="Paid",
        exception="None",
    ),
    Enrollment(
        enrollment_id=2,
        student_id=2,
        session_id=1,
        reg_date=datetime(2026, 1, 13),
        completed=False,
        payment_status="Pending",
        exception="None",
    ),
    Enrollment(
        enrollment_id=3,
        student_id=3,
        session_id=1,
        reg_date=datetime(2026, 1, 13),
        completed=True,
        payment_status="Paid",
        exception="Schedule conflict",
    ),
    Enrollment(
        enrollment_id=4,
        student_id=4,
        session_id=1,
        reg_date=datetime(2026, 1, 23),
        completed=True,
        payment_status="Paid",
        exception="None",
    ),
    Enrollment(
        enrollment_id=5,
        student_id=5,
        session_id=1,
        reg_date=datetime(2025, 12, 22),
        completed=True,
        payment_status="Paid",
        exception="CNext",
    ),
    Enrollment(
        enrollment_id=6,
        student_id=6,
        session_id=1,
        reg_date=datetime(2025, 12, 7),
        completed=True,
        payment_status="Paid",
        exception="None",
    ),
    Enrollment(
        enrollment_id=7,
        student_id=7,
        session_id=2,
        reg_date=datetime(2026, 1, 22),
        completed=True,
        payment_status="Paid",
        exception="None",
    ),
    Enrollment(
        enrollment_id=8,
        student_id=8,
        session_id=3,
        reg_date=datetime(2026, 2, 11),
        completed=False,
        payment_status="Pending",
        exception="None",
    ),
]
